<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="etapa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="longitud"/>
        <xs:element ref="fecha"/>
        <xs:element ref="tiempo_ganador"/>
        <xs:element ref="velocidad_media"/>
        <xs:element ref="desnivel"/>
        <xs:element ref="lugar_salida"/>
        <xs:element ref="lugar_meta"/>
        <xs:element ref="tipo"/>
        <xs:element ref="referencias"/>
        <xs:element ref="fotografias"/>
        <xs:element ref="videos"/>
        <xs:element ref="podcasts"/>
        <xs:element ref="salida"/>
        <xs:element ref="meta"/>
        <xs:element ref="hitos"/>
        <xs:element ref="clasificacion_etapa"/>
        <xs:element ref="clasificacion_general"/>
        <xs:element ref="clasificacion_equipos"/>
      </xs:sequence>
      <xs:attribute name="numero" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="longitud">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="fecha">
    <xs:complexType mixed="true">
      <xs:attribute name="formato" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tiempo_ganador">
    <xs:complexType mixed="true">
      <xs:attribute name="formato" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="velocidad_media">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="desnivel">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="lugar_salida" type="xs:string"/>
  <xs:element name="lugar_meta" type="xs:string"/>
  <xs:element name="tipo" type="xs:string"/>
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="referencia"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:string"/>
  <xs:element name="fotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="fotografia"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fotografia" type="xs:string"/>
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="video"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video" type="xs:string"/>
  <xs:element name="podcasts">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="podcast"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podcast" type="xs:string"/>
  <xs:element name="salida" type="coordenadas"/>
  <xs:element name="meta" type="coordenadas"/>
  <xs:complexType name="coordenadas">
    <xs:sequence>
      <xs:element ref="coordenadas"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="latitud"/>
        <xs:element ref="longitud"/>
        <xs:element ref="altitud"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="latitud">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="altitud">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="hitos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="hito"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hito">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="coordenadas">
          <xs:sequence>
            <xs:element ref="distancia_salida"/>
          </xs:sequence>
          <xs:attribute name="nombre"/>
          <xs:attribute name="tipo" use="required"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="distancia_salida">
    <xs:complexType mixed="true">
      <xs:attribute name="unidad" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion_etapa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion_general">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificacion_equipos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
        <xs:element ref="clasificado"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clasificado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element minOccurs="0" ref="diferencia_tiempo"/>
      </xs:sequence>
      <xs:attribute name="posicion" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="diferencia_tiempo">
    <xs:complexType mixed="true">
      <xs:attribute name="formato" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
